#!/usr/bin/env bash

# 检查 ctrl 的释放事件
# ps -ef | grep "xcape -e Control_L Escape" | grep -v "grep"
pgrep -f "xcape -e Control_L Escape"
if [ $? -ne 0 ]; then
    echo "remap Control_L to Escape"
    xcape -e "Control_L=Escape"
fi

# 检查 shift 的释放事件
# ps -ef | grep "xcape -e Shift_L F19" | grep -v "grep"
pgrep -f "xcape -e Shift_L F19"
if [ $? -ne 0 ]; then
    echo "remap Shift_L to F19"
    xcape -e "Shift_L=F19"
fi
